stack = []
stack.append("h")
stack.append("e")
stack.append("l")
stack.append("l")
stack.append("o")
stack.append("w")
stack.append("o")
stack.append("r")
stack.append("l")
stack.append("d")
print stack.pop()
